version: '3.3'

services:
  database:
    image: postgres:13.1
    container_name: futbol.database
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: deploy
      POSTGRES_DB: futbol_test
    ports:
      - "5432:5432"
